[workspace]
resolver = "2"
members = [
    "stm32-data-gen",
    "stm32-data-serde",
    "stm32-metapac-gen",
    "stm32-data-macros",
]
exclude = [
    "build"
]

# Optimize for dev experience: shortest "build+run" time after making a small change.
[profile.release]
debug = true
incremental = true
panic = 'abort'
opt-level = 2
