[toolchain]
channel = "nightly-2024-01-01"
components = [ "rust-src", "rustfmt" ]
targets = [
    "thumbv6m-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv8m.main-none-eabihf",
]
